version: "3"
services:
  hazelcast1:
    image: hazelcast/hazelcast:5.3.8
    container_name: hazelcast1
    ports:
      - "5701:5701"
    environment:
      - JAVA_OPTS=-Dhazelcast.cluster.name=dev
    networks:
      - hazelcast-net

  hazelcast2:
    image: hazelcast/hazelcast:5.3.8
    container_name: hazelcast2
    ports:
      - "5702:5701"
    environment:
      - JAVA_OPTS=-Dhazelcast.cluster.name=dev
    networks:
      - hazelcast-net

  hazelcast3:
    image: hazelcast/hazelcast:5.3.8
    container_name: hazelcast3
    ports:
      - "5703:5701"
    environment:
      - JAVA_OPTS=-Dhazelcast.cluster.name=dev
    networks:
      - hazelcast-net

  hazelcast4:
    image: hazelcast/hazelcast:5.3.8
    container_name: hazelcast4
    ports:
      - "5704:5701"
    environment:
      - JAVA_OPTS=-Dhazelcast.cluster.name=dev
    networks:
      - hazelcast-net

  worker0:
    build: .
    environment:
      - WORKER_ID=0
    networks:
      - hazelcast-net

  worker1:
    build: .
    environment:
      - WORKER_ID=1
    networks:
      - hazelcast-net

  worker2:
    build: .
    environment:
      - WORKER_ID=2
    networks:
      - hazelcast-net

  worker3:
    build: .
    environment:
      - WORKER_ID=3
    networks:
      - hazelcast-net

networks:
  hazelcast-net:
    driver: bridge
