version: '3.8'

networks:
  hazelcast-net:
    driver: bridge

services:
  hazelcast-node1:
    build:
      context: .
      dockerfile: Dockerfile.hazelcast-node
    container_name: hazelcast-node1
    networks:
      - hazelcast-net
    ports:
      - "5701:5701"

  hazelcast-node2:
    build:
      context: .
      dockerfile: Dockerfile.hazelcast-node
    container_name: hazelcast-node2
    networks:
      - hazelcast-net

  hazelcast-node3:
    build:
      context: .
      dockerfile: Dockerfile.hazelcast-node
    container_name: hazelcast-node3
    networks:
      - hazelcast-net

  hazelcast-node4:
    build:
      context: .
      dockerfile: Dockerfile.hazelcast-node
    container_name: hazelcast-node4
    networks:
      - hazelcast-net

  matrix-client:
    build:
      context: .
      dockerfile: Dockerfile.matrix-client
    container_name: matrix-client
    networks:
      - hazelcast-net
    depends_on:
      - hazelcast-node1
      - hazelcast-node2
      - hazelcast-node3
      - hazelcast-node4
    volumes:
      - ./results:/app/results
